mynotes/urls.py
from django.contrib import admin
from django.urls import path
from.views import index
from .import views
import django.contrib.auth.views as auth_views

app_name='mynotes'

urlpatterns=[
path('',index,name='index'),
path('home/',views.home,name='home'),
path('add-note/',views.add_note,name='add_note'),
path('register/',views.register,name='register'),
path('login/',views.userlogin,name='login'),
path('account/',views.account_settings,name='account_settings'),

path('logout/',auth_views.LogoutView.as_view(template_name='mynotes/logout.html'),name='logout'),
path('error/',views.reg_error,name='reg_error'),
path('update/<int:pk>/',views.update,name='update'),
path('delete/<int:pk>/',views.delete,name='delete'),
path('search/',views.search_note,name='search'),

]

note_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mynotes.urls'),name='mynotes')
]
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mynotes/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.





class Note(models.Model):
    title=models.CharField(max_length=100,null=False)
    description=models.TextField(null=False)
    time=models.DateTimeField(auto_now_add=True)
    complete=models.BooleanField(default=True)
    author=models.ForeignKey(User, on_delete=models.CASCADE , null=True, blank=True)
    

    def __str__(self):
        return self.title


        

mynotes/forms.py
from django import forms
from .models import  Note
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import Textarea, TextInput, PasswordInput





class MyUserRegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields= ['username', 'password1', 'password2', ]
        widgets = {
            'password1':PasswordInput(
                attrs={
                   
                   "class":"form-control"
                }
            ),
        
            'username':TextInput(
                attrs={
                   "placeholder": "Enter username",
                   "class":"form-control"
                }
            ),
             
            
         }



class NoteCreationForm(forms.ModelForm):
    title = forms.CharField(max_length=50, widget=forms.TextInput(attrs = {
        "class": "form-control", "placeholder": "Enter Title"
    }))

    description = forms.CharField(max_length=10000, widget=forms.Textarea(attrs = {
        "class": "form-control", "placeholder": "Enter Description", "rows": "8"
    }))
    class Meta:
        model=Note
        fields=['title','description']

class NoteUpdateForm(forms.ModelForm):
    title = forms.CharField(max_length=50, widget=forms.TextInput(attrs = {
        "class": "form-control", "placeholder": "Enter Title"
    }))

    description = forms.CharField(max_length=10000, widget=forms.Textarea(attrs = {
        "class": "form-control", "placeholder": "Enter Description", "rows": "8"
    }))
    class Meta:
        model=Note
        fields=['title','description']
        

class AccountSettingsForm(UserCreationForm):
    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs = {
        "class": "form-control", "placeholder": "Username"
    }))

    password1 = forms.CharField(max_length=50, widget=forms.TextInput(attrs = {
        "class": "form-control", "placeholder": "New password"
    }))

    password2 = forms.CharField(max_length=50, widget=forms.TextInput(attrs = {
        "class": "form-control", "placeholder": "Confirm password"
    }))

    
    first_name = forms.CharField( widget=forms.TextInput(attrs={
        'placeholder': 'First name', 'class':'form-control'
    }))

    last_name = forms.CharField( widget=forms.TextInput(attrs={
        'placeholder': 'Last name', 'class':'form-control'
    }))
    class Meta:
        model=User
        fields=['username', 'password1', 'password2', 'first_name', 'last_name' ]        

mynotes/views.py
from django.shortcuts import render,redirect
from .models import Note
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import NoteCreationForm,NoteUpdateForm,AccountSettingsForm,  MyUserRegistrationForm
from django.db.models import Q
#Create your views here.



 
def userlogin(request):
    if request.user.is_authenticated:
        return redirect('mynotes:home')
    if request.method=='POST':
        username = request.POST.get('username')
        #email.lower()
        password = request.POST.get('password')
        user=authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('mynotes:home')
        else:
             messages.success(request,"error in logging in")
    
    return render(request,'mynotes/login.html') 

def index(request):
    if request.user.is_authenticated:
        return redirect('mynotes:home')
    return render(request,'mynotes/index.html')


def register(request):
    form=MyUserRegistrationForm()
    context={'form':form}
    if request.method == 'POST':
        form = MyUserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()           
            user.save()
            messages.success(request,"Account created successfully!")
            login(request, user)
            return redirect('mynotes:home')
        else:
                messages.error(request, "An error occurred during registration, please try again!")
                return redirect('mynotes:reg_error')
           #login(request, user)
            #return redirect('mynotes/login.html')
        #else:
           # messages.error(request, 'An error occurred during registration')
           # return redirect('mynotes:reg_error')
    return render(request, 'mynotes/register.html',context )

@login_required
def home(request):
    mynotes=Note.objects.filter(author=request.user.id)
    search=request.GET.get('q') if request.GET.get('q')!=None else ''
    mynotes=mynotes.filter(
        
        Q(title__icontains=search)|
        Q(description__icontains=search)
    
        )
    
    count=mynotes.count()
    if count==0:
        check=False
    else:
        check=True
    context={
        'mynotes':mynotes,
        'count':count,
        'check':check
        
    }
    return render(request,'mynotes/home.html',context)       

def add_note(request):
    form=NoteCreationForm()

    if request.method == "POST":
        form=NoteCreationForm(request.POST)

        if form.is_valid():
            note_obj=form.save(commit=False)
            note_obj.author=request.user
            note_obj.save()

            return redirect('mynotes:home')
    context={'form':form}
    return render(request,'mynotes/addnote.html',context)      


@login_required
def account_settings(request):
    
    user=request.user

    form=AccountSettingsForm(instance=user)

    if request.method == "POST":
        form=AccountSettingsForm(request.POST, instance=user)
        if form.is_valid():
            user.save()

       # user.username=request.POST["name"]
        #user.first_name=request.POST["username"]
        #user.last_name=request.POST["email"]

        messages.success(request,"Account Updated Successfully")

        return redirect("mynotes:account_settings")
    context={
        'form':form,
        'user':user
    }
    return render(request,'mynotes/account.html', context) 

def logout(request):
    #return render(request,'mynotes/logout.html')
    return redirect('logout')

def reg_error(request):
    return render(request,'mynotes/reg_error.html')   

@login_required
def update(request, pk):
    note_to_update=Note.objects.get(pk=pk)
    form=NoteUpdateForm(instance=note_to_update)

    if request.method == "POST":
        form=NoteUpdateForm(request.POST)

        if form.is_valid():
            note_to_update.title=form.cleaned_data["title"]
            note_to_update.description=form.cleaned_data["description"]

            note_to_update.save()

            return redirect('mynotes:home')

    context={
        'note':note_to_update,
        'updateform':form
    }
    return render(request,'mynotes/update.html', context)  

    
@login_required
def delete(request, pk):
    note_to_delete=Note.objects.get(pk=pk)
    form=NoteUpdateForm(instance=note_to_delete)

    if request.method == "POST":

       note_to_delete.delete()
       messages.info(request, "Note has been deleted succesfuly")
       return redirect('mynotes:home')

    context={
        'note':note_to_delete,
        'deleteform':form
    }

    return render(request,'mynotes/delete.html', context)      

def search_note(request):
    if request.method == 'POST':
        search_value = request.POST['search']
        notes=Note.objects.filter(title__icontains = search_value) | Note.objects.filter(description__icontains = search_value)
        return redirect('mynotes:home')
    
    return render(request, 'search.html', {'notes':mynotes})
 

mynotes/templates/mynotes/addnote.html
	{% extends 'base.html' %}
	{% block body %}
<div class="container mt-3">
<div class='row align-content-center'>
    <div class="col-md-6">
        <h2>Add Note</h2>
    <div class="form">
        <form action="" method="post">
            {% csrf_token %}
        

            {{ form.as_p }}
         <br>
            <div class="form-group">
                <a href="{%url 'mynotes:home'%}" class="btn btn-success">Back</a>
                <button type="submit" class="btn btn-primary">Save</button>
               
            </div>
            <br>
        </form>
    </div>
    </div>
</div>
</div>
{%endblock%}

mynotes/templates/mynotes/delete.html
	{% extends 'base.html' %}
	{% block body %}
<div class="container mt-5">
<div class='row align-content-center'>
    <div class="col-md-6">
        <h2>Are you sure you want to delete?</h2>
    <div class="form">
        <form action="" method="post">
            {% csrf_token %}
        

            {{ form.as_p }}
         <br>
            <div class="form-group">
                <button type="submit" class="btn btn-danger">Yes</button>
                <a href="{%url 'mynotes:home'%}" class="btn btn-success">Cancel</a>
               
            </div>
            <br>
        </form>
    </div>
    </div>
</div>
</div>
{%endblock%}

mynotes/templates/mynotes/home.html
<!--
	Author: W3layouts
	Author URL: http://w3layouts.com
	License: Creative Commons Attribution 3.0 Unported
	License URL: http://creativecommons.org/licenses/by/3.0/
-->


	<!--//header-->

	<!--/banner-->
	{% extends 'base.html' %}
	{% block body %}
	

	
	<div class="container"> 
		

		<br>{% if messages %}
				{% for message in messages %}
					 <p class="alert alert-{{message.tags}}">{{message}}</p>
				{% endfor %}
				
			{% endif %}	
		
			{% if check %}
			<h2>Recent Notes</h2>
			
			{%else%}
			<h2>Please add a note!</h2>
			{%endif%}
        <div class="row">
            <div class="col-md-6 ">

{% for note in mynotes %}
           
<h5 class="text-info pt-2">{{note.title}}</h5>
<p>{{note.description | truncatechars:"200" | linebreaks }}</p>
	
<div class="options">
	<a href="{% url 'mynotes:update' note.id%}" class="btn btn-success">Edit</a>
	<a href="/delete/{{note.id}}/" class="btn btn-danger">Delete</a>
</div>
<br>
<h6>Created: <strong>{{note.time | timesince}}</strong></h6>
<hr>
{%empty%}
<h4 class='text-info my-3'>No note found....</h4>
{% endfor %}
			</div>
			
		</div> 
		<p> No of notes : {{count}}</p>
		</div>

	</div>
	<br>
	<br>
  

		{% endblock body %}
		
		

mynotes/templates/mynotes/index.html
<!--
	Author: W3layouts
	Author URL: http://w3layouts.com
	License: Creative Commons Attribution 3.0 Unported
	License URL: http://creativecommons.org/licenses/by/3.0/
-->


	<!--//header-->

	<!--/banner-->
	{% extends 'base.html' %}
	{% block body %}
	<br>
	<section class="py-5 text-center container">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">My Notes</h1>
            <p class="lead text-muted">This is a note keeping app built for the sole purpose of writing and saving notes.</p>
            <p>
              <a href="{% url 'mynotes:register' %}" class="btn btn-primary my-2">Create an account</a>
              <a href="{% url 'mynotes:login' %}" class="btn btn-secondary my-2">Login</a>
            </p>
          </div>
        </div>
      </section>

		{% endblock body %}
		
		<!--//main-->
	<!--footer-->
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-lg-4 footer-grid-agileits-w3ls text-left">
					<h3>About US</h3>
					<p>Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. lacinia eget consectetur sed, convallis at tellus..</p>
					<div class="read">
						<a href="single.html" class="btn btn-primary read-m">Read More</a>
					</div>
				</div>
				<div class="col-lg-4 footer-grid-agileits-w3ls text-left">

					<div class="tech-btm">
						<h3>Latest Posts</h3>
						<div class="blog-grids row mb-3">
							<div class="col-md-5 blog-grid-left">
								<a href="single.html">
									<img src="images/4.jpg" class="img-fluid" alt="">
								</a>
							</div>
							<div class="col-md-7 blog-grid-right">

								<h5>
									<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
								</h5>
								<div class="sub-meta">
									<span>
										<i class="far fa-clock"></i> 20 Jan, 2018</span>
								</div>
							</div>
							
						</div>
						<div class="blog-grids row mb-3">
							<div class="col-md-5 blog-grid-left">
								<a href="single.html">
									<img src="images/5.jpg" class="img-fluid" alt="">
								</a>
							</div>
							<div class="col-md-7 blog-grid-right">

								<h5>
									<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
								</h5>
								<div class="sub-meta">
									<span>
										<i class="far fa-clock"></i> 20 Jan, 2018</span>
								</div>
							</div>
							
						</div>
						<div class="blog-grids row mb-3">
							<div class="col-md-5 blog-grid-left">
								<a href="single.html">
									<img src="images/6.jpg" class="img-fluid" alt="">
								</a>
							</div>
							<div class="col-md-7 blog-grid-right">

								<h5>
									<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
								</h5>
								<div class="sub-meta">
									<span>
										<i class="far fa-clock"></i> 20 Jan, 2018</span>
								</div>
							</div>
							
						</div>
					</div>
				</div>
				<!-- subscribe -->
				<div class="col-lg-4 subscribe-main footer-grid-agileits-w3ls text-left">
					<h2>Signup to our newsletter</h2>
					<div class="subscribe-main text-left">
							<div class="subscribe-form">
									<form action="#" method="post" class="subscribe_form">
										<input class="form-control" type="email" placeholder="Enter your email..." required="">
										<button type="submit" class="btn btn-primary submit">Submit</button>
									</form>
									<div class="clearfix"> </div>
						   </div>
						<p>We respect your privacy.No spam ever!</p>
					</div>
					<!-- //subscribe -->
				</div>
			</div>
			<!-- footer -->
			<div class="footer-cpy text-center">
				<div class="footer-social">
					<div class="copyrighttop">
						<ul>
							<li class="mx-3">
								<a class="facebook" href="#">
									<i class="fab fa-facebook-f"></i>
									<span>Facebook</span>
								</a>
							</li>
							<li>
								<a class="facebook" href="#">
									<i class="fab fa-twitter"></i>
									<span>Twitter</span>
								</a>
							</li>
							<li class="mx-3">
								<a class="facebook" href="#">
									<i class="fab fa-google-plus-g"></i>
									<span>Google+</span>
								</a>
							</li>
							<li>
								<a class="facebook" href="#">
									<i class="fab fa-pinterest-p"></i>
									<span>Pinterest</span>
								</a>
							</li>
						</ul>

					</div>
				</div>
				<div class="w3layouts-agile-copyrightbottom">
					<p>© 2018 Weblog. All Rights Reserved | Design by
						<a href="http://w3layouts.com/">W3layouts</a>
					</p>

				</div>
			</div>

			

			<!-- //footer -->
		</div>
	</footer>
	<!---->
	<!-- js -->
	<script src="js/jquery-2.2.3.min.js"></script>
	<!-- //js -->
	<!-- desoslide-JavaScript -->
	<script src="js/jquery.desoslide.js"></script>
	<script>
		$('#demo1_thumbs').desoSlide({
			main: {
				container: '#demo1_main_image',
				cssClass: 'img-responsive'
			},
			effect: 'sideFade',
			caption: true
		});
	</script>

	<!-- requried-jsfiles-for owl -->
	<script>
		$(window).load(function () {
			$("#flexiselDemo1").flexisel({
				visibleItems: 3,
				animationSpeed: 1000,
				autoPlay: true,
				autoPlaySpeed: 3000,
				pauseOnHover: true,
				enableResponsiveBreakpoints: true,
				responsiveBreakpoints: {
					portrait: {
						changePoint: 480,
						visibleItems: 1
					},
					landscape: {
						changePoint: 640,
						visibleItems: 2
					},
					tablet: {
						changePoint: 768,
						visibleItems: 3
					}
				}
			});

		});
	</script>
	<script>
		$(window).load(function () {
			$("#flexiselDemo2").flexisel({
				visibleItems: 3,
				animationSpeed: 1000,
				autoPlay: true,
				autoPlaySpeed: 3000,
				pauseOnHover: true,
				enableResponsiveBreakpoints: true,
				responsiveBreakpoints: {
					portrait: {
						changePoint: 480,
						visibleItems: 1
					},
					landscape: {
						changePoint: 640,
						visibleItems: 2
					},
					tablet: {
						changePoint: 768,
						visibleItems: 3
					}
				}
			});

		});
	</script>
	<script src="js/jquery.flexisel.js"></script>
	<!-- //password-script -->
	<!--/ start-smoth-scrolling -->
	<script src="js/move-top.js"></script>
	<script src="js/easing.js"></script>
	<script>
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();
				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 900);
			});
		});
	</script>
	<!--// end-smoth-scrolling -->

	<script>
		$(document).ready(function () {
			
									var defaults = {
							  			containerID: 'toTop', // fading element id
										containerHoverID: 'toTopHover', // fading element hover id
										scrollSpeed: 1200,
										easingType: 'linear' 
							 		};
									

			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});
	</script>
	<a href="#home" class="scroll" id="toTop" style="display: block;">
		<span id="toTopHover" style="opacity: 1;"> </span>
	</a>

	<!-- //Custom-JavaScript-File-Links -->
	<script src="js/bootstrap.js"></script>

mynotes/templates/mynotes/login.html
<!--
	Author: W3layouts
	Author URL: http://w3layouts.com
	License: Creative Commons Attribution 3.0 Unported
	License URL: http://creativecommons.org/licenses/by/3.0/
-->

{% extends 'base.html' %}
{% block body %}
	
	<section class="main-content-w3layouts-agileits">
		<div class="container">
			
			
				<h3 class="tittle">Sign into your account</h3>
				<div class="row inner-sec">
					<div class="login p-5 bg-light mx-auto mw-100">
						<form action="" method="POST" >
							{%csrf_token%}
							<div class="form-group">
							  <label for="exampleInputEmail1 mb-2">Username</label>
							  <input type="text" name='username' class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter username" required="">
							  
							</div>
							<div class="form-group">
							  <label for="exampleInputPassword1 mb-2">Password</label>
							  <input type="password" name='password' class="form-control" id="exampleInputPassword1" placeholder="Enter password" required="">
							</div>
							<div class="form-check mb-2">
							  <input type="checkbox" class="form-check-input" id="exampleCheck1">
							  <label class="form-check-label" for="exampleCheck1">Remember me</label>
							</div>
							<button type="submit" class="btn btn-primary submit mb-4">Sign In</button>
							<p><a href="{% url 'mynotes:register' %}"> Don't have an account?</a></p>
						  </form>
		</div>
		</div>
	</div>
	</section>
	{% endblock body %}
	
	<!--//main-->
	<!--footer-->
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-lg-4 footer-grid-agileits-w3ls text-left" data-aos="fade-down">
					<h3>About US</h3>
					<p>Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. lacinia eget consectetur sed, convallis at tellus..</p>
					<div class="read">
						<a href="single.html" class="btn btn-primary read-m">Read More</a>
					</div>
				</div>
				<div class="col-lg-4 footer-grid-agileits-w3ls text-left">

					<div class="tech-btm" data-aos="fade-down">
						<h3>Latest Posts</h3>
						<div class="blog-grids row mb-3">
							<div class="col-md-5 blog-grid-left">
								<a href="single.html">
									<img src="images/4.jpg" class="img-fluid" alt="">
								</a>
							</div>
							<div class="col-md-7 blog-grid-right">

								<h5>
									<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
								</h5>
								<div class="sub-meta">
									<span>
										<i class="far fa-clock"></i> 20 Jan, 2018</span>
								</div>
							</div>

						</div>
						<div class="blog-grids row mb-3" data-aos="fade-down">
							<div class="col-md-5 blog-grid-left">
								<a href="single.html">
									<img src="images/5.jpg" class="img-fluid" alt="">
								</a>
							</div>
							<div class="col-md-7 blog-grid-right">

								<h5>
									<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
								</h5>
								<div class="sub-meta">
									<span>
										<i class="far fa-clock"></i> 20 Jan, 2018</span>
								</div>
							</div>

						</div>
						<div class="blog-grids row mb-3" data-aos="fade-down">
							<div class="col-md-5 blog-grid-left">
								<a href="single.html">
									<img src="images/6.jpg" class="img-fluid" alt="">
								</a>
							</div>
							<div class="col-md-7 blog-grid-right">

								<h5>
									<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
								</h5>
								<div class="sub-meta">
									<span>
										<i class="far fa-clock"></i> 20 Jan, 2018</span>
								</div>
							</div>

						</div>
					</div>
				</div>
				<!-- subscribe -->
				<div class="col-lg-4 subscribe-main footer-grid-agileits-w3ls text-left" data-aos="fade-down">
					<h2>Signup to our newsletter</h2>
					<div class="subscribe-main text-left">
							<div class="subscribe-form">
									<form action="#" method="post" class="subscribe_form">
										<input class="form-control" type="email" placeholder="Enter your email..." required="">
										<button type="submit" class="btn btn-primary submit">Submit</button>
									</form>
									<div class="clearfix"> </div>
							</div>
						<p>We respect your privacy.No spam ever!</p>
					</div>
					<!-- //subscribe -->
				</div>
			</div>
			<!-- footer -->
			<div class="footer-cpy text-center">
				<div class="footer-social">
					<div class="copyrighttop">
						<ul>
							<li class="mx-3">
								<a class="facebook" href="#">
									<i class="fab fa-facebook-f"></i>
									<span>Facebook</span>
								</a>
							</li>
							<li>
								<a class="facebook" href="#">
									<i class="fab fa-twitter"></i>
									<span>Twitter</span>
								</a>
							</li>
							<li class="mx-3">
								<a class="facebook" href="#">
									<i class="fab fa-google-plus-g"></i>
									<span>Google+</span>
								</a>
							</li>
							<li>
								<a class="facebook" href="#">
									<i class="fab fa-pinterest-p"></i>
									<span>Pinterest</span>
								</a>
							</li>
						</ul>

					</div>
				</div>
				<div class="w3layouts-agile-copyrightbottom">
					<p>© 2018 Weblog. All Rights Reserved | Design by
						<a href="http://w3layouts.com/">W3layouts</a>
					</p>

				</div>
			</div>

			<!-- //footer -->
		</div>
	</footer>
	<!---->
	<!-- js -->
	<script src="js/jquery-2.2.3.min.js"></script>
	<!-- //js -->
	<!--/ start-smoth-scrolling -->
	<script src="js/move-top.js"></script>
	<script src="js/easing.js"></script>
	<script>
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();
				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 900);
			});
		});
	</script>
	<!--// end-smoth-scrolling -->

	<script>
		$(document).ready(function () {
			/*
									var defaults = {
							  			containerID: 'toTop', // fading element id
										containerHoverID: 'toTopHover', // fading element hover id
										scrollSpeed: 1200,
										easingType: 'linear' 
							 		};
									*/

			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});
	</script>
	<a href="#home" class="scroll" id="toTop" style="display: block;">
		<span id="toTopHover" style="opacity: 1;"> </span>
	</a>

	<!-- //Custom-JavaScript-File-Links -->
	<script src="js/bootstrap.js"></script>


</body>

</html>

mynotes/templates/mynotes/logout.html
<!--
	Author: W3layouts
	Author URL: http://w3layouts.com
	License: Creative Commons Attribution 3.0 Unported
	License URL: http://creativecommons.org/licenses/by/3.0/
-->

{% extends 'base.html' %}
{% block body %}
<section class="py-5 text-center container">
	<div class="row py-lg-5">
	  <div class="col-lg-6 col-md-8 mx-auto">
		<h1 class="fw-light">You have Logged Out!</h1>
		
		<p>
		  <a href="{% url 'mynotes:login' %}" class="btn btn-secondary my-2">Login Again</a>
		</p>
	  </div>
	</div>
  </section>

	{% endblock body%}
	
	<!--//main-->
	<!--footer-->
	


</body>

</html>

mynotes/templates/mynotes/reg_error.html
    
{% extends 'base.html' %}
{% block body %}


{% if messages %}
{% for message in messages %}
         <h2 class="alert alert-{{message.tags}}">{{message}}</h2>
{% endfor %}

{% endif %}	
       <div class="form-group">
       <a href="{%url 'mynotes:register'%}" class="btn btn-success">Go back</a>
          </div>   
               <br>
                    



        {% endblock body%}

mynotes/templates/mynotes/search.html
{% extends 'base.html' %}
	{% block body %}

	
	<div class="container"> 
		
		<br>
		
        <h1>Recent Notes</h1>
        <div class="row">
            <div class="col-md-6 ">
{% if notes %}
{% for note in mynotes %}
           
<h2 class="text-info pt-2">{{note.title}}</h2>
<p>{{note.description}}</p>
<div class="options">
	<a href="{% url 'mynotes:update' note.id%}" class="btn btn-success">Edit</a>
	<a href="/delete/{{note.id}}/" class="btn btn-danger">Delete</a>
</div>
<br>
<h6>Created: <strong>{{note.time | timesince}}</strong></h6>
<hr>
{% endfor %}
{% else %}
<h4 class = "msg bg-light">Note not found!</h4>
			</div>
           
		</div> 
        </div>
    </div>
{% endif %}
  

		{% endblock body %}

mynotes/templates/mynotes/update.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        
        <div class="col-md-9">
            <br>
            <h2 class="text-dark">Update Note</h2>
        
    <div class="form">
        
         <form action="" method="POST">
             {% csrf_token %}
             {{updateform.as_p}}
             <hr>
             <button type="submit" class="btn-info btn">Update</button>
         </form>
    </div>
</div>
</div>
 </div>
 <br>
 <br>

{% endblock body%}