mynotes/urls.py
from django.contrib import admin
from django.urls import path
from.views import index
from .import views
import django.contrib.auth.views as auth_views

app_name='mynotes'

urlpatterns=[
path('',index,name='index'),
path('home/',views.home,name='home'),
path('add-note/',views.add_note,name='add_note'),
path('register/',views.register,name='register'),
path('login/',views.userlogin,name='login'),
path('account/',views.account_settings,name='account_settings'),

path('logout/',auth_views.LogoutView.as_view(template_name='mynotes/logout.html'),name='logout'),
path('error/',views.reg_error,name='reg_error'),
path('update/<int:pk>/',views.update,name='update'),
path('delete/<int:pk>/',views.delete,name='delete'),
path('search/',views.search_note,name='search'),

]

note_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mynotes.urls'),name='mynotes')
]
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mynotes/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.





class Note(models.Model):
    title=models.CharField(max_length=100,null=False)
    description=models.TextField(null=False)
    time=models.DateTimeField(auto_now_add=True)
    complete=models.BooleanField(default=True)
    author=models.ForeignKey(User, on_delete=models.CASCADE , null=True, blank=True)
    

    def __str__(self):
        return self.title


        

mynotes/forms.py
from django import forms
from .models import  Note
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import Textarea, TextInput, PasswordInput





class MyUserRegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields= ['username', 'password1', 'password2', ]
        widgets = {
            'password1':PasswordInput(
                attrs={
                   
                   "class":"form-control"
                }
            ),
        
            'username':TextInput(
                attrs={
                   "placeholder": "Enter username",
                   "class":"form-control"
                }
            ),
             
            
         }



class NoteCreationForm(forms.ModelForm):
    title = forms.CharField(max_length=50, widget=forms.TextInput(attrs = {
        "class": "form-control", "placeholder": "Enter Title"
    }))

    description = forms.CharField(max_length=10000, widget=forms.Textarea(attrs = {
        "class": "form-control", "placeholder": "Enter Description", "rows": "8"
    }))
    class Meta:
        model=Note
        fields=['title','description']

class NoteUpdateForm(forms.ModelForm):
    title = forms.CharField(max_length=50, widget=forms.TextInput(attrs = {
        "class": "form-control", "placeholder": "Enter Title"
    }))

    description = forms.CharField(max_length=10000, widget=forms.Textarea(attrs = {
        "class": "form-control", "placeholder": "Enter Description", "rows": "8"
    }))
    class Meta:
        model=Note
        fields=['title','description']
        

class AccountSettingsForm(UserCreationForm):
    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs = {
        "class": "form-control", "placeholder": "Username"
    }))

    password1 = forms.CharField(max_length=50, widget=forms.TextInput(attrs = {
        "class": "form-control", "placeholder": "New password"
    }))

    password2 = forms.CharField(max_length=50, widget=forms.TextInput(attrs = {
        "class": "form-control", "placeholder": "Confirm password"
    }))

    
    first_name = forms.CharField( widget=forms.TextInput(attrs={
        'placeholder': 'First name', 'class':'form-control'
    }))

    last_name = forms.CharField( widget=forms.TextInput(attrs={
        'placeholder': 'Last name', 'class':'form-control'
    }))
    class Meta:
        model=User
        fields=['username', 'password1', 'password2', 'first_name', 'last_name' ]        

mynotes/views.py
from django.shortcuts import render,redirect
from .models import Note
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import NoteCreationForm,NoteUpdateForm,AccountSettingsForm,  MyUserRegistrationForm
from django.db.models import Q
#Create your views here.



 
def userlogin(request):
    if request.user.is_authenticated:
        return redirect('mynotes:home')
    if request.method=='POST':
        username = request.POST.get('username')
        #email.lower()
        password = request.POST.get('password')
        user=authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('mynotes:home')
        else:
             messages.success(request,"error in logging in")
    
    return render(request,'mynotes/login.html') 

def index(request):
    if request.user.is_authenticated:
        return redirect('mynotes:home')
    return render(request,'mynotes/index.html')


def register(request):
    form=MyUserRegistrationForm()
    context={'form':form}
    if request.method == 'POST':
        form = MyUserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()           
            user.save()
            messages.success(request,"Account created successfully!")
            login(request, user)
            return redirect('mynotes:home')
        else:
                messages.error(request, "An error occurred during registration, please try again!")
                return redirect('mynotes:reg_error')
           #login(request, user)
            #return redirect('mynotes/login.html')
        #else:
           # messages.error(request, 'An error occurred during registration')
           # return redirect('mynotes:reg_error')
    return render(request, 'mynotes/register.html',context )

@login_required
def home(request):
    mynotes=Note.objects.filter(author=request.user.id)
    search=request.GET.get('q') if request.GET.get('q')!=None else ''
    mynotes=mynotes.filter(
        
        Q(title__icontains=search)|
        Q(description__icontains=search)
    
        )
    
    count=mynotes.count()
    if count==0:
        check=False
    else:
        check=True
    context={
        'mynotes':mynotes,
        'count':count,
        'check':check
        
    }
    return render(request,'mynotes/home.html',context)       

def add_note(request):
    form=NoteCreationForm()

    if request.method == "POST":
        form=NoteCreationForm(request.POST)

        if form.is_valid():
            note_obj=form.save(commit=False)
            note_obj.author=request.user
            note_obj.save()

            return redirect('mynotes:home')
    context={'form':form}
    return render(request,'mynotes/addnote.html',context)      


@login_required
def account_settings(request):
    
    user=request.user

    form=AccountSettingsForm(instance=user)

    if request.method == "POST":
        form=AccountSettingsForm(request.POST, instance=user)
        if form.is_valid():
            user.save()

       # user.username=request.POST["name"]
        #user.first_name=request.POST["username"]
        #user.last_name=request.POST["email"]

        messages.success(request,"Account Updated Successfully")

        return redirect("mynotes:account_settings")
    context={
        'form':form,
        'user':user
    }
    return render(request,'mynotes/account.html', context) 

def logout(request):
    #return render(request,'mynotes/logout.html')
    return redirect('logout')

def reg_error(request):
    return render(request,'mynotes/reg_error.html')   

@login_required
def update(request, pk):
    note_to_update=Note.objects.get(pk=pk)
    form=NoteUpdateForm(instance=note_to_update)

    if request.method == "POST":
        form=NoteUpdateForm(request.POST)

        if form.is_valid():
            note_to_update.title=form.cleaned_data["title"]
            note_to_update.description=form.cleaned_data["description"]

            note_to_update.save()

            return redirect('mynotes:home')

    context={
        'note':note_to_update,
        'updateform':form
    }
    return render(request,'mynotes/update.html', context)  

    
@login_required
def delete(request, pk):
    note_to_delete=Note.objects.get(pk=pk)
    form=NoteUpdateForm(instance=note_to_delete)

    if request.method == "POST":

       note_to_delete.delete()
       messages.info(request, "Note has been deleted succesfuly")
       return redirect('mynotes:home')

    context={
        'note':note_to_delete,
        'deleteform':form
    }

    return render(request,'mynotes/delete.html', context)      

def search_note(request):
    if request.method == 'POST':
        search_value = request.POST['search']
        notes=Note.objects.filter(title__icontains = search_value) | Note.objects.filter(description__icontains = search_value)
        return redirect('mynotes:home')
    
    return render(request, 'search.html', {'notes':mynotes})
 

mynotes/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
	<title>Mynotebook application</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<meta name="keywords" content="Weblog a Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />

	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<link href="{% static 'mynotes/css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
	
	<link href="{% static 'mynotes/css/jquery.desoslide.css' %}" rel="stylesheet">
	<link href="{% static 'mynotes/css/style.css' %}" rel='stylesheet' type='text/css' />
	<link href="{% static 'mynotes/css/fontawesome-all.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" integrity="sha384-xeJqLiuOvjUBq3iGOjvSQSIlwrpqjSHXpduPd6rQpuiM3f5/ijby8pCsnbu5S81n" crossorigin="anonymous">
	<link href="/fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800"
	    rel="stylesheet">
</head>

<body> 
	<!--Header-->

	<header>
		



		         
		<div class="top-bar_sub_w3layouts container-fluid">
			<div class="row">
				<div class="col-md-4 logo text-left">
					<a class="navbar-brand" href="{% url 'mynotes:index' %}">
						<i class="bi bi-pen"></i> Mynotes</a>
						
				</div>
				<div class="col-md-4 top-forms text-center mt-lg-3 mt-md-1 mt-0">
					{% if request.user.is_authenticated %}
					Welcome! {{request.user.username}}
					
					{% endif %}
					
					</ul>
				</div>
			</div>
		</div>

			<div class="header_top" id="home">
				<nav class="navbar navbar-expand-lg navbar-light bg-light">
					<button class="navbar-toggler navbar-toggle-right mx-auto" type="button" data-bs-toggle="collapse" data-bs-target="#menu" 
							 aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
				   </button>

				   <div class="collapse navbar-collapse" id="menu">
					<ul class="navbar-nav mr-auto">
						{% if request.user.is_authenticated %}
						<li class="nav-item active">
							<a class="nav-link" href="{% url 'mynotes:home' %}">Home
								<span class="sr-only">(current)</span>
							</a>
						</li>
					
						<li class="nav-item">
							<a class="nav-link" href="{% url 'mynotes:add_note' %}">+Add Notes</a>
						</li>
						
						<li class="nav-item">
							<a class="nav-link" href="{% url 'mynotes:account_settings' %}">Settings</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="{% url 'mynotes:logout' %}">Logout</a>
						</li>
							{% else %}
							<li class="nav-item active">
								<a class="nav-link" href="{% url 'mynotes:index' %}">Home
									<span class="sr-only">(current)</span>
								</a>
							</li>
						
							<li class="nav-item">
								<a class="nav-link" href="{% url 'mynotes:register' %}">Register</a>
							</li>
							
							<li class="nav-item">
								<a class="nav-link" href="{% url 'mynotes:login' %}">Login</a>
							</li>
							{% endif %}

					</ul>
				</div>
				{% if request.user.is_authenticated %}
				<form action="" method="GET" class="form-inline my-2 my-lg-0 header-search">
					{% csrf_token %}
					<input class="form-control mr-sm-2" type="search" placeholder="Search for notes here..." name="q" required="">
					<button class="btn btn1 my-2 my-sm-0" type="submit">
						<i class="bi bi-search"></i>
					</button>
					
				</form>
				{% endif%}
			</div>
			
		
			
		</div>
				
					</div>
				</nav>

			</div>
	</header>
	

    {% block body %}
	{% endblock body%}




	<!-- Footer -->
<footer class="bg-dark text-center text-white">
	<!-- Grid container -->
	<div class="container p-4">
	  <!-- Section: Social media -->
	  <section class="mb-4">
		<!-- Whatsaap -->
		<a class="btn btn-outline-light btn-floating m-1" href="https://wa.me/2348098116023" role="button"
		  ><i class="bi bi-whatsapp"></i
		></a>
  
		<!-- Twitter -->
		<a class="btn btn-outline-light btn-floating m-1" href="https://twitter.com/mjayb_" role="button"
		  ><i class="bi bi-twitter"></i
		></a>
  
		<!-- Google -->
		<a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
		  ><i class="bi bi-google"></i
		></a>
  
		<!-- Instagram -->
		<a class="btn btn-outline-light btn-floating m-1" href="https://instagram.com/mjayb__?igshid=YmMyMTA2M2Y=" role="button"
		  ><i class="bi bi-instagram"></i
		></a>
  
		<!-- Linkedin -->
		<a class="btn btn-outline-light btn-floating m-1" href="https://www.linkedin.com/in/maryjane-amarachi-538271250" role="button"
		  ><i class="bi bi-linkedin"></i
		></a>
  
		<!-- Github -->
		<a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
		  ><i class="bi bi-github"></i
		></a>
	  </section>
	  <!-- Section: Social media -->
  
	  <!-- Section: Form -->
	  <section class="">
		<form action="">
		  <!--Grid row-->
		  <div class="row d-flex justify-content-center">
			<!--Grid column-->
			<div class="col-auto">
			  <p class="pt-2 text-white">
				<strong>Sign up for our newsletter</strong>
			  </p>
			</div>
			<!--Grid column-->
  
			<!--Grid column-->
			<div class="col-md-5 col-12">
			  <!-- Email input -->
			  <div class="form-outline form-white mb-4">
				<input type="email" id="form5Example21" class="form-control" />
				<label class="form-label" for="form5Example21">Email address</label>
			  </div>
			</div>
			<!--Grid column-->
  
			<!--Grid column-->
			<div class="col-auto">
			  <!-- Submit button -->
			  <button type="submit" class="btn btn-outline-light mb-4">
				Subscribe
			  </button>
			</div>
			<!--Grid column-->
		  </div>
		  <!--Grid row-->
		</form>
	  </section>
	  <!-- Section: Form -->
  
	  <!-- Section: Text -->
	  <section class="mb-4">
		<p  class="text-white">
			Short notes are quick to write and correct, tightly focused, and easy to review, and can be read (and comprehended) rapidly; therefore, they have the potential to reach a wide audience.
		</p>
	  </section>
	  <!-- Section: Text -->
  
	 
	<!-- Grid container -->
  
	<!-- Copyright -->
	<div class="text-center p-3 text-white" style="background-color: rgba(0, 0, 0, 0.2);">
		&copy All Rights Reserved By
		<span ><a  class="text-primary" href="#">RYMATECH CONSULT</a></span>
	</div>
	
	<!-- Copyright -->
  </footer>
  <!-- Footer -->

	
	
</body>

</html>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>